CREATE TABLE IF NOT EXISTS tirages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    date_tirage TEXT NOT NULL,
    n1 INTEGER, n2 INTEGER, n3 INTEGER, n4 INTEGER, n5 INTEGER, n6 INTEGER, n7 INTEGER,
    boni INTEGER
);
